FROM node:22-alpine

WORKDIR /app

# Копируем только package.json и yarn.lock для кэширования
COPY package.json yarn.lock ./

# Устанавливаем зависимости (этот слой кэшируется!)
RUN yarn install --frozen-lockfile

# НЕ копируем исходники - они будут через volume
# COPY . .

# Prisma + Nest watch
CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && yarn start:dev"]
