FROM node:22-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

RUN yarn global add prisma

COPY . .

RUN yarn prisma generate

CMD ["sh", "-c", "npx prisma migrate dev --name init --skip-seed && yarn start:dev"]
